# Generated by Django 5.1.2 on 2024-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree', models.CharField(max_length=200)),
                ('plat_principal', models.TextField(max_length=200)),
                ('garniture', models.TextField(max_length=200)),
                ('produit_laitier_ou_divers', models.TextField(max_length=200)),
                ('dessert', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
