# Generated by Django 5.1.2 on 2024-10-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_receipt_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='dessert',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='entree',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='garniture',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='produit_laitier_ou_divers',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
